FROM ruby:3.4.9-slim

WORKDIR /rails

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential curl git libsqlite3-0 libsqlite3-dev libyaml-dev nodejs npm pkg-config && \
    npm install -g yarn && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

COPY Gemfile Gemfile.lock package.json yarn.lock ./

RUN bundle install
RUN yarn install

COPY . .

EXPOSE 3000
